---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbit-manage
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    controllers:
      main:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: "@hourly"
          timeZone: ${TIMEZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        containers:
          app:
            command:  # New: Bypass entrypoint
              - qbit_manage
            # No 'args' needed; env vars control behavior
            env:
              TZ: ${TIMEZONE}
              QBT_CONFIG_DIR: /config
              QBT_CONFIG_FILE: /config/config.yml  # Explicit for safety
              QBT_RUN: "true"  # Triggers run mode
            envFrom:
              - secretRef:
                  name: qbittorrent-login
            image: *image
            resources: *resources
            securityContext:
              <<: *securityContext
              readOnlyRootFilesystem: false  # Allow any writes (e.g., temp logs)
      recheck:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: "@daily"
        containers:
          app:
            command:
              - qbit_manage
            env:
              TZ: ${TIMEZONE}
              QBT_CONFIG_DIR: /config
              QBT_CONFIG_FILE: /config/config.yml
              QBT_RECHECK: "true"  # Triggers recheck mode
            envFrom:
              - secretRef:
                  name: qbittorrent-login
            image: *image
            resources: *resources
            securityContext:
              <<: *securityContext
              readOnlyRootFilesystem: false
      trim:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: "@daily"
        # Explicitly ensure no initContainers (app-template default is none)
        initContainers: []  # Add this empty array to override any template default
        containers:
          app:
            command:
              - sh
              - -c
              - |
                pip install --no-cache-dir qbittorrent-api && python /config/trim_seeders.py  # --no-cache to minimize writes
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: qbittorrent-login
            image:
              repository: python
              tag: 3.12-slim
            resources: *resources
            securityContext:
              <<: *securityContext
              readOnlyRootFilesystem: false
        pod:
          automountServiceAccountToken: false
          securityContext:
            runAsGroup: 0
            runAsNonRoot: false
            runAsUser: 0
            seccompProfile: { type: RuntimeDefault }

    persistence:
      config-dir:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config
      config-file:
        enabled: true
        type: configMap
        name: qbit-manage-configmap
        mountPath: /config/config.yml
        subPath: config.yml
        readOnly: true
      trim-script:
        enabled: true
        type: configMap
        name: qbittorrent-trim-script
        globalMounts:
          - path: /config/trim_seeders.py
            subPath: trim_seeders.py
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /media
