---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbit-manage-configmap
data:
  config.yml: |
    qbt:
      host: qbittorrent.media.svc.cluster.local:80
      user: !ENV QBT_USER
      pass: !ENV QBT_PASS

    directory:
      remote_dir: /media
      recycle_bin: /media/.RecycleBin
      orphaned_dir: /media/orphaned_data

    tracker:
      iptorrents.com:  # Adjust if the tracker URL keyword is different
        tag: iptorrents
      stackoverflow.tech:
        tag: iptorrents
      empirehost.me:
        tag: iptorrents
      bgp.technology:
        tag: iptorrents

    share_limits:
      ipt:
        priority: 1
        include_any_tags: ["iptorrents"]
        max_ratio: 1.1
        max_seeding_time: 337h
        cleanup: true
        min_seeding_time: 0h
        min_num_seeds: 0
        resume_torrent_after_change: true
        add_group_to_tag: false

    recyclebin:
      enable: true
      empty_after_x_days: 7
      save_torrents: false
      split_by_category: false

    orphaned:
      empty_after_x_days: 7
      exclude_patterns: ["*/incomplete/*", "*/manual/*"]
      max_orphaned_files_to_delete: 50
      min_file_age_minutes: 0

    settings:
      force_auto_tmm: false
      force_auto_tmm_ignore_tags: []
      tracker_error_tag: issue
      nohardlinks_tag: noHL
      share_limits_tag: ~share_limit
      share_limits_min_seeding_time_tag: MinSeedTimeNotReached
      share_limits_min_num_seeds_tag: MinSeedsNotMet
      share_limits_last_active_tag: LastActiveLimitNotReached
      cat_filter_completed: true
      share_limits_filter_completed: true
      tag_nohardlinks_filter_completed: true
      cat_update_all: true
      disable_qbt_default_share_limits: true
      tag_stalled_torrents: true
      stalled_tag: stalledDL
      rem_unregistered_grace_minutes: 10
      rem_unregistered_ignore_list: []
