apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: flux-system
type: Opaque
stringData:
  users: |
    zach:$2y$05$gzzSFMbkrZ3xvvLj7PTD9e.gGQNYQVuIk0FIc5vHSDlZE2qdG94nu
    kevin:$2y$05$IgYibDYXOYVsfVT2ohjrjOrzF3mZSQ4VpqOps12TaQNNE6fYrgJGa
