apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-basic-auth
spec:
  basicAuth:
    secret: basic-auth-secret
    realm: "Restricted Area"  # Optional: Customizes the popup’s message
