---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-downloads-pv
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.2
    path: /mnt/ssd/downloads
  claimRef:
    namespace: media
    name: nfs-downloads-pvc
  mountOptions:
    - nfsvers=4.2
    - nconnect=16
    - hard
    - noatime
    - rsize=1048576
    - wsize=1048576

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-downloads-pvc
  namespace: media
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-downloads-pv
