apiVersion: v1
kind: Service
metadata:
  name: gluetun-http
  namespace: media
spec:
  selector:
    app.kubernetes.io/name: sabnzbd
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: ClusterIP

# Used for HTTP Proxy connection in -arr apps. Connects to sabnzbd's gluetun sidecar.
