---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.2
    path: /mnt/OlsonNAS/nfs/media
  claimRef:
    namespace: media           # <-- Explicitly bind to the `media` namespace
    name: nfs-media-pvc        # <-- Explicitly bind to the PVC named `nfs-media-pvc`
  mountOptions:
    - nfsvers=4.2
    - nconnect=16
    - hard
    - noatime
    # - fsc                    # Enables NFSv4 filesystem caching (data/attrs in kernel cache)
    # - actimeo=600            # 10-min attribute cache timeout (reduces metadata roundtrips; tune to 300-1800s based on file changes)
    # - rsize=1048576          # 1MB read block size (boosts sequential reads for media streaming/seeding)
    # - wsize=1048576          # 1MB write block (less relevant for seeding, but balances if you upload logs)

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: media             # Must match Sonarr's namespace, media
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi             # Match PV's capacity
  volumeName: nfs-media-pv     # Explicitly bind to the PV
