---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.2
    path: "/mnt/OlsonNAS/nfs/media"
  claimRef:
    namespace: media        # <-- Explicitly bind to the `media` namespace
    name: nfs-media-pvc     # <-- Explicitly bind to the PVC named `nfs-media-pvc`
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-pvc
  namespace: media          # Must match Sonarr's namespace, media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi             # Match PV's capacity
  volumeName: nfs-media-pv     # Explicitly bind to the PV
