# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:rJzT39SCB/ey3hxONz8rZYSHpQqi/RfgxCSmr3FyUo8=,iv:nCTh3ajI3QKgofQnEOt0tAdzzqUqmuoFsb4DrPsxwwk=,tag:MLrEpNcK36zKta9SBe8fFQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZDM1SVdROVZPbk91QlJC
        aEpORmFXcXdzc0cwTjcvcklWV0h4VFVNazFBCjlVdHRtM2c0ZCs3Z1hFbXltbEVC
        bDhCU3JvditZWTB3czVLT0M3KzN3MEUKLS0tIFdKV3ZmTitwdi9WeHg3YU0zMXYw
        Z3graGFmUm5EblFwTWZnQUFhYzZHbDgKw+PGrjVLFUOcbfbkD+qDcYXOnFfa0gIo
        hVWHcSzsqrI9D/rsw8JCzASchJbtyZzqZNhxS8c0I2tExr/I/BO7DQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-18T03:19:10Z"
  mac: ENC[AES256_GCM,data:Z48iBArBvA4rBpxQO8Fk9CBOFDrYPUWDrrPYvlBI8Ns4/smfAywM6U2kOB9ZChi2W1MgpxJXjVahz6H4cVWCZn11n1sj+eRZMbKE+3XQO/WrYJGs31kkqw7FoQJ8zhwfzR5l3Piv7dxR1Bvn/0t3KqI+Yk/3CoCYo4FKfDABL2E=,iv:ZJWDmYJOWf0OiS4kU06SeH5KmJyUrhbP1e8z1NgsT3s=,tag:Lvb4d5lFTXSBj2Xd4LPbwQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
