---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jellyseerr-db
  namespace: media
spec:
  refreshInterval: 1m  # Sync every minute
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: jellyseerr-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres-pguser-jellyseerr # Name of kubernetes secret in database namespace
        property: password
