---
fullnameOverride: coredns
k8sAppLabelOverride: kube-dns
serviceAccount:
  create: true
service:
  name: kube-dns
  clusterIP: "10.96.0.10"
replicaCount: 2
servers:
  - zones:
      - zone: ${SECRET_DOMAIN}  # Placeholder - Flux will replace this
    port: 53
    scheme: dns://
    use_tcp: true
    plugins:
      - name: forward
        parameters: . ${IPAM_IP_ADGUARDHOME_INTERNAL} # All queries for SECRETDOMAIN go here
  - zones:
      - zone: .
        scheme: dns://
        use_tcp: true
    port: 53
    plugins:
      - name: errors
      - name: health
        configBlock: |-
          lameduck 5s
      - name: ready
      - name: log
        configBlock: |-
          class error
      - name: prometheus
        parameters: 0.0.0.0:9153
      - name: kubernetes
        parameters: cluster.local in-addr.arpa ip6.arpa
        configBlock: |-
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
      - name: forward
        parameters: . 1.1.1.1 8.8.8.8
      - name: cache
        parameters: 30
      - name: loop
      - name: reload
      - name: loadbalance
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
