kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: vaultwarden-secret
  namespace: flux-system
stringData:
  ADMIN_TOKEN: ENC[AES256_GCM,data:el33iADRJFYjEnvC1JefrJMUnc59V5pWfm3MwTI8Xp7kjpLEpFEbHA==,iv:bc188IE316pvhv3fDXKrrGQX2GTm3ZC9+lvsNtnTWQg=,tag:Mpc16yqU8FrhvAra1M+d7Q==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubHBxSG9weDNQMlZrQU5H
        UHpPK08xQUwyY1N6SXcxSVNiVFE5dDg3MWxzCjNRbE9JR0d3eDRua3FGNm9qazlp
        N2M0aGRISlVseUVoVTVpSWpIcnZCa3cKLS0tIHlualhaU3V5SXRRQUZzK1k5VjV5
        V29uQklKQjdnTE1TOGNNNi9JS2hmQXcK2gT2SYbOnZRPeWkj1yZxItTRDxojJdwX
        ubtGPhl0xQNT+r9LLtZH+W11TdEn2+GTMoipTVUKc10KD4I3r/Uz+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-13T02:55:13Z"
  mac: ENC[AES256_GCM,data:TjFz4LzBFiBMunsXhdUFS609cjQSzly8jHgKEiZasKH13mivrbnWjpGoICI/WwujCNtvjUWmtEMsTCJmIRhjQuDW6fYLXK0EysNtRrdxesO1VtcghIPVc7AHGjCLN+HCwzLkKvUtjopAeHdZi7cnASH7vH2C9tY5LIK7ku8bQjw=,iv:GGKHGdQN5OVILvgMn2yjkWwuj3l84hbydJErraHKSDc=,tag:wJ+4K4bf8OdHCqIvmhEivA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
