---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pgbackrest-pv
spec:
  storageClassName: nfs-csi
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.2
    path: /mnt/OlsonNAS/nfs/backups/postgres-cluster
  mountOptions:
    - nfsvers=4.2
    - nconnect=16
    - hard
    - noatime

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: nfs-postgres-pvc
#   namespace: database             # Must match Sonarr's namespace, media
# spec:
#   storageClassName: nfs-csi
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Mi             # Match PV's capacity
#   volumeName: nfs-postgres-pv     # Explicitly bind to the PV
