# sops_secrets/pgbackrest-encryption.yaml
apiVersion: v1
kind: Secret
metadata:
  name: crunchy-postgres-secret
  namespace: database
stringData:
  repo1-cipher-pass: ENC[AES256_GCM,data:VRj7U+qWmeWbSduogRSWPttrPnUBjlXpmwLFTrn5Qws=,iv:JTVg8yXuNFw3HXpmxnw3dE5eLIU9yuxhy0l5oa6qsD0=,tag:c9tM4fdVhuH0fYiED6uZUA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWGVXem1vcnBYMzVmZVBx
        N3Z4aG5EY0VrRWxFRm82S3Brc0J0V3pqSVQ0Ck9aQ0lpbmVjZnowVzhPUEJjZURH
        eVpwOGMzQ29vam5jWFRaQktzY2Y2YWsKLS0tIENXTjhtOFIzN2M2M3ZWUHl6S0xQ
        RW9lMko1N1B5VEthN3dsdm5hTlJyS2MKkY1/o1IPNSM1HPOvMFMelmGkuHNLCwle
        P0PyfXlqQ0X/6RqLWgFMvFwjJAEmsyMLESp/Y052hAwIx0+j9GBvyA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T02:36:04Z"
  mac: ENC[AES256_GCM,data:0UhRy51T0SiLG/b0cEUtZp3fGHd/G8ZCR2zrnBEX6OCJZ6pdmsOpnk3m80H/kHU76crcxyVvdkGPnUxePMS0sTKASUyFDGD4j1m9W0dNnnvJl1Y4PuE/7SAdUED9+x53yEozQgSXIeMD4ZO/rEnNTLkld+KpNN3IYVUTdWNWtIs=,iv:8RELcsMrskvP26Ipg1j8oit1lmOIcuV0WNuJo1m9Ahw=,tag:IJ7wgf3vu37ADBBo9mkt8w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
