apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: crunchy-postgres-secret
  namespace: flux-system
stringData:
  repo1-cipher-pass: ENC[AES256_GCM,data:Ue5EmyVZ7TxXMwQUml6Gx6BLg/LLh18rVdIb72fAWRU=,iv:4nccpGhimlPQMi7ZiVoW0h1iehmffd99kKflCLaDKBY=,tag:BbFSa0mi7yaF9bwyIpg1BA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERTIvVkZtdXVqVUpoYU5T
        eTVGdVgwMFNWOTQ3eE5hZUFtWWIyVi9UNjEwCmErQmZZWjZsNTN4c1I2ekNmY0NB
        c3puRm5rZzZMR1hoclBLemc1bXhGQ2sKLS0tIEk2WExJRlZ0a21BYS9DOXAzK2xU
        bmZzR0E4VXpDOUsyaVgvbm13cjAvQ0UK0j8uog2gckLlw+v4v8+Xo5d0QhC4cM2o
        pPEdwc3BAsJ4uXgzfc+dO7vRxNmgJnqlSOBuSq8ZAAyeBl3XYOUZKA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-20T04:55:29Z"
  mac: ENC[AES256_GCM,data:AxOku+7cxOrOkB45suv2FnyWCyPok8ZhzKMUUX8AEKuUoef9k2NnTY0/X7QG509as22ybvxoFLNNs5EKgKUog66+jA/q8UqalaKEmBTfUnEdFWdweOdFdxwZJgtfzcvnGbd3dL9O8LMQhYtYKJ7UCXbiiaXXujVIDmVzjUcg1DY=,iv:XWXVQwO4K1SKjTtGpDHa2wyX1lZTTZsQksGqg4LPAsU=,tag:TMqKrY5WSMKTenv95Mt9+A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
