# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-driver-nfs
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs
        namespace: flux-system
  values:
    kubeletDir: /var/lib/kubelet
    nfs:
      server: 192.168.1.2
      path: /mnt/OlsonNAS/kubernetes/appdata
