apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media
spec:
  capacity:
    storage: 25Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  nfs:
    server: 192.168.1.2
    path: /mnt/OlsonNAS/kubernetes/media
  claimRef:
    namespace: media  # <-- Explicitly bind to the `media` namespace
    name: nfs-media    # <-- Explicitly bind to the PVC named `nfs-media`
