---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-data
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  nfs:
    server: 192.168.1.2
    path: /mnt/OlsonNAS/kubernetes/data
