apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media
  namespace: media          # Must match Sonarr's namespace, media
spec:
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Ti         # Match PV's capacity
  volumeName: nfs-media     # Explicitly bind to the PV
