---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.2
  path: /mnt/OlsonNAS/docker
reclaimPolicy: Retain
volumeBindingMode: Immediate
