---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
    - name: generic-device-plugin
      namespace: kube-system
  values:
    controllers:
      qbittorrent:
        annotations:
          secret.reloader.stakater.com/reload: qbittorrent

        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65534

        initContainers:
          init-run:
            image:
              repository: busybox
              tag: latest
            command:
              - /bin/sh
              - -c
              - |
                mkdir -p /run
                chown 1001:1001 /run
                chmod 755 /run
            securityContext:
              runAsUser: 0  # Root privileges for init

        containers:
          wireguard-pia:
            image:
              repository: ghcr.io/thrnz/docker-wireguard-pia
              tag: latest
            env:
              TZ: ${TIMEZONE}
              PORT_FORWARDING: "1"
              PORT_FILE: /pia-shared/port.dat
              PORT_PERSIST: "1"
              RECONNECT: "1"
              HEALTHCHECK_PING_TARGET: 8.8.8.8
              LOCAL_NETWORK: "10.69.0.0/16,10.96.0.0/16"
              MTU: 1420
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 50m
                memory: 50M
              limits:
                cpu: 200m
                memory: 100M
                squat.ai/tun: 1

          qbittorrent:
            dependsOn: wireguard-pia
            image:
              repository: linuxserver/qbittorrent
              tag: 5.1.2
            env:
              TZ: ${TIMEZONE}
              UMASK: "022"
              WEBUI_PORT: &port 80
            resources:
              requests:
                cpu: 100m
                memory: 2048M
              limits:
                cpu: 1000m
                memory: 4096M
            securityContext:
              runAsUser: 0
              runAsGroup: 1001
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              # capabilities:
              #   drop:
              #     - ALL

          port-sync:
            image:
              repository: curlimages/curl
              tag: latest
            command:
              - /bin/sh
              - -c
              - |
                while ! curl --output /dev/null --silent --head --fail --connect-timeout 1 http://localhost:80; do sleep 5; done
                sleep 10
                PREV_PORT=0
                while true; do
                  if [ -f /pia-shared/port.dat ]; then
                    NEW_PORT=$(cat /pia-shared/port.dat)
                    if [ "$NEW_PORT" != "$PREV_PORT" ]; then
                      curl -s --cookie-jar /tmp/qb-cookies.txt \
                        -u "$QBIT_USER:$QBIT_PASS" \
                        http://localhost:80/api/v2/auth/login
                      curl -s --cookie /tmp/qb-cookies.txt -X POST \
                        "http://localhost:80/api/v2/app/setPreferences" \
                        -H "Content-Type: application/x-www-form-urlencoded" \
                        -d "json={\"listen_port\": $NEW_PORT}"
                      echo "Updated qBittorrent port to $NEW_PORT"
                      PREV_PORT=$NEW_PORT
                    fi
                  fi
                  sleep 300
                done
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            dependsOn: qbittorrent
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 24M
              limits:
                cpu: 50m
                memory: 50M

          # vuetorrent:
          #   dependsOn: qbittorrent
          #   image:
          #     repository: registry.k8s.io/git-sync/git-sync
          #     tag: v4.4.0
          #   args:
          #     - --repo=https://github.com/WDaan/VueTorrent
          #     - --ref=latest-release
          #     - --period=86400s
          #     - --root=/addons
          #   resources:
          #     requests:
          #       cpu: 50m
          #       memory: 37M

          cjratliff-ui:
            dependsOn: qbittorrent
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.4.0
            args:
              - --repo=https://github.com/Carve/qbittorrent-webui-cjratliff.com
              - --ref=stable
              - --period=86400s
              - --root=/addons
            resources:
              requests:
                cpu: 20m
                memory: 32M

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: *port

    ingress:
      qbittorrent:
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth@kubernetescrd"
        hosts:
          - host: &host qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_DOMAIN/./-}-production-tls"

    persistence:
      config:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 2Gi
        advancedMounts:
          qbittorrent:
            qbittorrent:
              - path: /config
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /media
      downloads:
        enabled: true
        existingClaim: nfs-downloads-pvc
        globalMounts:
          - path: /downloads
      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-sync:
              - path: /config
      addons:
        type: emptyDir
        globalMounts:
          - path: /addons
      pia-shared:
        enabled: true
        type: emptyDir
        advancedMounts:
          qbittorrent:
            wireguard-pia:
              - path: /pia-shared
            qbittorrent:
              - path: /pia-shared
            port-sync:
              - path: /pia-shared
      run:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            init-run:
              - path: /run
            qbittorrent:
              - path: /run
