---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
    - name: generic-device-plugin
      namespace: kube-system
  values:
    controllers:
      qbittorrent:
        annotations:
          secret.reloader.stakater.com/reload: qbittorrent

        pod:
          securityContext:
            fsGroup: 1001
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65534

        containers:
          wireguard-pia:
            image:
              repository: ghcr.io/thrnz/docker-wireguard-pia
              tag: latest  # Pin to a version like 2024.09.24 if needed
            env:
              TZ: ${TIMEZONE}
              PORT_FORWARDING: "1"
              PORT_FILE: /pia-shared/port.dat
              PORT_PERSIST: "1"  # Keeps same port across restarts
              RECONNECT: "1"  # Auto-regen on drops
              HEALTHCHECK_PING_TARGET: 8.8.8.8
              LOCAL_NETWORK: "10.69.0.0/16,10.96.0.0/16"
              MTU: 1420
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 50m
                memory: 50M
              limits:
                cpu: 200m
                memory: 100M
                squat.ai/tun: 1

          qbittorrent:
            dependsOn: wireguard-pia
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 5.0.3
            env:
              TZ: ${TIMEZONE}
              UMASK: "022"
              QBITTORRENT__PORT: 8080
              QBITTORRENT__BT_PORT: &bittorrentPort 50413  # Initial; will be updated dynamically
              QBT_BitTorrent__Session__Interface: wg0
              QBT_BitTorrent__Session__InterfaceAddress: 0.0.0.0
              QBT_BitTorrent__Session__InterfaceName: wg0
            resources:
              requests:
                cpu: 50m
                memory: 2408M
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL

          # CHANGED: Renamed/updated from port-forward to port-sync; custom for file-based update via qBittorrent API
          port-sync:
            image:
              repository: alpine  # Lightweight; uses built-in curl/apk if needed
              tag: latest
            command:
              - /bin/sh
              - -c
              - |
                apk add --no-cache curl nc-openbsd
                while ! nc -z localhost 8080; do sleep 5; done
                sleep 10
                PREV_PORT=50413
                while true; do
                  if [ -f /pia-shared/port.dat ]; then
                    NEW_PORT=$(cat /pia-shared/port.dat)
                    if [ "$NEW_PORT" != "$PREV_PORT" ]; then
                      curl -s --cookie-jar /tmp/qb-cookies.txt \
                        -u "$QBIT_USER:$QBIT_PASS" \
                        http://localhost:8080/api/v2/auth/login
                      curl -s --cookie /tmp/qb-cookies.txt -X POST \
                        "http://localhost:8080/api/v2/app/setPreferences" \
                        -H "Content-Type: application/x-www-form-urlencoded" \
                        -d "json={\"listen_port\": $NEW_PORT}"
                      echo "Updated qBittorrent port to $NEW_PORT"
                      PREV_PORT=$NEW_PORT
                    fi
                  fi
                  sleep 300
                done
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            dependsOn: qbittorrent  # NEW: Sync after qBittorrent starts
            securityContext:
              runAsUser: 1001
              runAsGroup: 1001
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop:
                  - ALL
            resources:
              requests:
                cpu: 10m
                memory: 24M
              limits:
                cpu: 50m
                memory: 50M

          vuetorrent:
            dependsOn: qbittorrent
            image:
              repository: registry.k8s.io/git-sync/git-sync
              tag: v4.4.0
            args:
              - --repo=https://github.com/WDaan/VueTorrent
              - --ref=latest-release
              - --period=86400s
              - --root=/addons
            resources:
              requests:
                cpu: 50m
                memory: 37M

    # NEW: ConfigMap for port-sync script (if you want to externalize the command above; optional for now)
    # Create separately: kubectl apply -f - <<EOF
    # apiVersion: v1
    # kind: ConfigMap
    # metadata:
    #   name: qbittorrent-port-sync-script
    #   namespace: flux-system  # Adjust
    # data:
    #   sync-port.sh: |
    #     #!/bin/sh
    #     # (paste the script from command above)
    # EOF
    # Then in port-sync: volumeMounts for the CM, and command: ["/bin/sh", "/scripts/sync-port.sh"]

    service:
      app:
        controller: qbittorrent
        ports:
          http:
            port: 8080

    ingress:
      qbittorrent:
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth@kubernetescrd"
        hosts:
          - host: &host qbittorrent.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_DOMAIN/./-}-production-tls"

    persistence:
      config:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 2Gi
        advancedMounts:
          qbittorrent:
            qbittorrent:
              - path: /config
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /media
      empty-config:
        type: emptyDir
        advancedMounts:
          qbittorrent:
            port-sync:
              - path: /config
      addons:
        type: emptyDir
        globalMounts:
          - path: /addons
      pia-shared:
        enabled: true
        type: emptyDir
        advancedMounts:
          qbittorrent:
            wireguard-pia:
              - path: /pia-shared
            qbittorrent:
              - path: /pia-shared
            port-sync:
              - path: /pia-shared
