kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: qbittorrent-secret
  namespace: flux-system
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:n4sSvRXBTpfTqslTIjSmU2tzA6CyJ7QlN+VgfBJR0q1l8mhFswp6jjVmtKs=,iv:pGR3wksuhegG+TNSuqtHKwYG/GAZ1R5AnH+QZA9DxIY=,tag:dwxTSN2psEx3EFOWfHrpOQ==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:/asCzG+EEIx2xL9oBA==,iv:HiSmDMo4dFc82W6VSfDIkO6gKz058U5mxxbdetj6f1g=,tag:7Y0Jnz6R9b7LZk7H4rWrvA==,type:str]
  SERVER_CITIES: ENC[AES256_GCM,data:gFoMHY97Ol6ruqTz/e4KDnkfuD7J9w==,iv:jmq7AYSMl+2wFiTuPVZOYEfKBAtzaGpuYcxnkKNACFI=,tag:Mep1XA+WFg4guaJwcadouA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZFJkU3BJcU5qUGNGNWwy
        QnFOc0ZEYXBuOHQxUE9NUENiZnV5bktSTUhJCjQ2QURMR21lZ2I5SG5XUldYNUZU
        TlNYay83VGV5MzN1UTd1OStEV0pkUXcKLS0tICs5VXJ6cktIc0ROSE5zeDhlSlMr
        ZHJwaGxrNS93K2lCeCtpUXhDV3Y3YlEKxtbJqhEI3NmFDgpUXhNAdV8hKfxDTFCw
        wEqz19lYsGi15H/z8f2ZJvvURL4sZguE1rn8da20Vc/YABuPCocrQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T08:28:03Z"
  mac: ENC[AES256_GCM,data:KmbFGMxUnPY5mBtRhY5jkjsMafi6GVGlyNhHOpPDLfPI/yeYz3uPWPABJjsHqiUulyvnZOCCqUCjNLq1FCXGXLx48PBRRBf8lvoy9LpDzI9rtNBdpKCngaa2ICkUZINmLWtydcDuLs105obt78StHPszV6OY50PFmr2eapnjGWY=,iv:AzpQKlJzEQPEfiScQGeGPZSc/pmlLyHPBU8gP5Nj39c=,tag:eQ2di6IgCjojzGoYuLoWxA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
