kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: qbittorrent-secret
  namespace: flux-system
stringData:
  USER: ENC[AES256_GCM,data:WoyKYdmjaZI=,iv:mMHf0s+KOUvJ6twomVpvEHzlSBRwastALelt4lkoFCI=,tag:ZlCAGF86FO1PPf+1rr7w6g==,type:str]
  PASS: ENC[AES256_GCM,data:vGu/kVNQkAcrdMOWYHGNlyk=,iv:h0kMwrBOCnJ2LmLFsimvXJrKz3QYUjeQoXu2xoAeSRY=,tag:owRfx9h8mu3UVfumjrIwFg==,type:str]
  LOC: ENC[AES256_GCM,data:I5ZG5Q8N,iv:xbNesx6Jw3GJMpGH94OZ2iOHsqhGLLL/JYHJ8u813Yw=,tag:IbO/g7ZoE9/YSqJKU6EnyA==,type:str]
  VPN_INTERFACE: ENC[AES256_GCM,data:TUN9,iv:zSOnWdF2pEAfUHBK8tFGl3L1cPXGYbmvxoICYqewPdY=,tag:HYPU4Rr9uBAos2cbfH0uXA==,type:str]
  QBIT_USER: ENC[AES256_GCM,data:tzMI/bY=,iv:ryqvFi2RwMDXMQht4BL089JJq2smZRNHyNv2WbVTFHU=,tag:Po26J6zkxeK4GkdtNoN/ng==,type:str]
  #ENC[AES256_GCM,data:jxEuCuEvYepodoSsbmMwJg==,iv:z6DxAtxokq2exOP1tp/fsGld7mFoL/dtwqItPHUAhzw=,tag:2DXhbW5Ev6kpz4sLSgXLsQ==,type:comment]
  QBIT_PASS: null
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZFJkU3BJcU5qUGNGNWwy
        QnFOc0ZEYXBuOHQxUE9NUENiZnV5bktSTUhJCjQ2QURMR21lZ2I5SG5XUldYNUZU
        TlNYay83VGV5MzN1UTd1OStEV0pkUXcKLS0tICs5VXJ6cktIc0ROSE5zeDhlSlMr
        ZHJwaGxrNS93K2lCeCtpUXhDV3Y3YlEKxtbJqhEI3NmFDgpUXhNAdV8hKfxDTFCw
        wEqz19lYsGi15H/z8f2ZJvvURL4sZguE1rn8da20Vc/YABuPCocrQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-24T13:09:12Z"
  mac: ENC[AES256_GCM,data:GIwy4pNXPgbj/HC1dtH32MFKOpMfR42jBXAwzN+Ma7mRPN1fVvKCCOwaA9CumP+9ajS2ajUw1IQwup8nRbg2ky5OQytBIT30/5gU5uYny5XeNt2fCHizg5OyvsFbj+DEpCDQavsPkG3yIFWeChbwBo4Sjkvcfut5TOspGA51404=,iv:94sjKuj8eQf5/EJWlZWe27IztYXb5+zwQQRjizQZwr0=,tag:QsayyoxADu6e24Lt/QdxqQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
