---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.0.1/charts/library/common/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: media
spec:
  releaseName: sonarr
  interval: 15m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.6.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
  values:
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/sonarr
              pullPolicy: IfNotPresent
              tag: 4.0.12.2823
            env:
              TZ: America/Detroit
              SONARR__INSTANCE_NAME: Sonarr
              SONARR__PORT: 8989
              SONARR__APPLICATION_URL: "https://sonarr.${SECRET_DOMAIN}"
              SONARR__LOG_LEVEL: info

    service:
      main:
        controller: main
        ports:
          http:
            port: 8989

    ingress:
      main:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth-restrict-networks@kubernetescrd"
        hosts:
          - host: "sonarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  port: http
        tls:
          - hosts:
              - "sonarr.${SECRET_DOMAIN}"
            secretName: "${SECRET_DOMAIN/./-}-production-tls"

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "Always"

    persistence:
      config:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteOnce
        size: 2Gi
        mountPath: /config
      media:
        enabled: true
        existingClaim: nfs-data
        globalMounts:
          - path: /data
