# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:BivsdhwGbZpJWXM=,iv:Quf/LLxtCxN+elY1jq0JncSG2rBTmX8KCC6R30/1404=,tag:vDxV6O8dNN0kVe/gsHA9Mg==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:tIpStbl/yxaXxNOcYORMx37Ly9s=,iv:VOtCjBHcr9VJBAjdfsuXvO1Ygz6fjnYREwAnL022U/k=,tag:zJD/09d2MpDHNdK79cXjJA==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:i3Ie5dd9IOGXe3Z24HeMW9qi555FDwlIV+yxo99yttB8txVR,iv:2dY6SUtBj2T8uerLPE2S8MiYGJO2aLBr6ZGtVzRvJi4=,tag:Ww6NS7PpQoahFEbquefOhQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVlpqd0NCNkZpYnQvZnd5
        WUpYeFVoSFVOaHNQcDRINEtYOWY3WG16UUMwClc1bnY4K1o2TGg4QS8rMHA5czFU
        NmtYaTMxZDYzdXFPL0RvTXVTZERvNGcKLS0tIE5KT1gybk0yUit1dUpUOW1qallC
        dndTSmhqR0FCT2ZjdTA2Ly9PZXFVNlkK0bsuZsTM1P4APU82XNHrRmdaROQhRWLO
        EzAMGhn63jdnOuSMdck50m+CUjeVn2NW9O2OKwNQRBF3X5nVCopgzQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-17T22:23:11Z"
  mac: ENC[AES256_GCM,data:ywtdiaOCiFK2myW6QUApvK8nU5/kxPqia3vtDrXc8RUN908k9ZnmZNn5Q7HIbdAQ9yl6UWl/RK7ji0QjUAhv28V/RbHxO02r9kGlqyJL3B6m6lLKLT/Mp2O+UJ6PNZ8cHNdtIXqsajkdEZDoJEybiABDQKKiP2+hkBN6k48HIYY=,iv:UWPf5J3W8v1WLOIZkIwHTEpePqwe0u5v210vMKEf40k=,tag:l15+ut+GM3Aaq3QSc02fZQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
