---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-db
  namespace: vault
spec:
  refreshInterval: 1m  # Sync every minute
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: nextcloud-db-secret
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: postgres-pguser-nextcloud
        property: username
    - secretKey: password
      remoteRef:
        key: postgres-pguser-nextcloud # Name of kubernetes secret in database namespace
        property: password
    - secretKey: host
      remoteRef:
        key: postgres-pguser-nextcloud
        property: host
    - secretKey: port
      remoteRef:
        key: postgres-pguser-nextcloud
        property: port
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud-tls-ca
  namespace: vault
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: crunchy-pgo-secrets
  target:
    name: nextcloud-tls-ca-secret
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: pgo-root-cacert
        property: root.crt
