# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prowlarr
  namespace: media
spec:
  releaseName: prowlarr
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: csi-driver-nfs
      namespace: kube-system
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/prowlarr
              pullPolicy: IfNotPresent
              tag: 1.30.2.4939
            env:
              - name: TZ
                value: "America/Detroit"
              - name: PROWLARR__INSTANCE_NAME
                value: "Prowlarr"
              - name: PROWLARR__PORT
                value: "8989"
              - name: PROWLARR__APPLICATION_URL
                value: "https://prowlarr.${SECRET_DOMAIN}"
              - name: PROWLARR__LOG_LEVEL
                value: "info"
    service:
      main:
        controller: main
        ports:
          http:
            port: 9696
    ingress:
      main:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth-restrict-networks@kubernetescrd"
        hosts:
          - host: "prowlarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - "prowlarr.${SECRET_DOMAIN}"
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      config:
        enabled: true
        storageClass: nfs-csi     # Dynamic PVC in /kubernetes/appdata
        accessMode: ReadWriteOnce
        size: 2Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        fsGroupChangePolicy: "Always"
