---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-tools
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: qbittorrent
      namespace: media
  values:
    controllers:
      tagging:
        type: cronjob
        cronjob: &cronJobSpec
          schedule: "@hourly"
          timeZone: ${TIMEZONE}
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        initContainers:
          01-tag:
            args:
              - tagging
              - --added-on
              - --expired
              - --last-activity
              - --not-working
              - --sites
              - --unregistered
              - --server
              - qbittorrent.media.svc.cluster.local
              - --port
              - "80"
              - --config
              - "/config/config.yaml"
            env: &env
              TZ: ${TIMEZONE}
            image: &image
              repository: ghcr.io/buroa/qbtools
              tag: v0.19.14@sha256:905617dfc1a8aa1510381d8e177cc5581a49bfa9d56f3f05e0574f6c83987d3c
            resources: &resources
              requests:
                cpu: 15m
                memory: 105M
              limits:
                cpu: 21m
                memory: 105M
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
          02-auto-prune:
            args:
              - prune
              - --include-tag
              - "auto-prune"
              - --include-tag
              - "expired"
              - --server
              - "qbittorrent.media.svc.cluster.local"
              - --port
              - "80"
            env: *env
            image: *image
            resources: *resources
            securityContext: *securityContext
          03-unmapped:
            args:
              - prune
              - --include-tag
              - "site:unmapped"
              - --server
              - "qbittorrent.media.svc.cluster.local"
              - --port
              - "80"
            env: *env
            image: *image
            resources: *resources
            securityContext: *securityContext
        containers:
          app:
            args:
              - prune
              - --exclude-category
              - manual
              - --include-tag
              - expired
              - --exclude-tag
              - activity:24h
              - --server
              - qbittorrent.media.svc.cluster.local
              - --port
              - "80"
            env: *env
            image: *image
            resources: *resources
            securityContext: *securityContext
        pod: &podSecurityContext
          automountServiceAccountToken: false
          securityContext:
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seccompProfile: { type: RuntimeDefault }
      orphaned:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: "@daily"
        containers:
          app:
            args:
              - orphaned
              - --exclude-pattern
              - "*/incomplete/*"
              - --exclude-pattern
              - "*/manual/*"
              - --server
              - "qbittorrent.media.svc.cluster.local"
              - --port
              - "80"
            env: *env
            image: *image
            resources: *resources
            securityContext:
              <<: *securityContext
        pod: *podSecurityContext
      prune-unregistered:
        type: cronjob
        cronjob:
          <<: *cronJobSpec
          schedule: "@daily"
        containers:
          app:
            args:
              - prune
              - --include-tag
              - unregistered
              - --exclude-tag
              - expired
              - --server
              - qbittorrent.media.svc.cluster.local
              - --port
              - "80"
            env: *env
            image: *image
            resources: *resources
            securityContext:
              <<: *securityContext
        pod: *podSecurityContext
      reannounce:
        containers:
          app:
            args:
              - reannounce
              - --process-seeding
              - -s
              - qbittorrent.media.svc.cluster.local
              - -p
              - "80"
            env: *env
            image: *image
            resources: *resources
            securityContext: *securityContext
        pod: *podSecurityContext

    persistence:
      config-file:
        enabled: true
        type: configMap
        name: qbittorrent-tools-configmap
        globalMounts:
          - path: /config/config.yaml
            subPath: config.yaml
      media:
        enabled: true
        existingClaim: nfs-media-pvc
        globalMounts:
          - path: /media
