# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plik
  namespace: media
spec:
  releaseName: plik
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        containers:
          main:
            image:
              repository: rootgg/plik
              tag: 1.3.8
            args:
              - -config
              - /plikd.cfg
            env:
              TZ: ${TIMEZONE}
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 512Mi
    configMaps:
      config-file:
        enabled: true
        data:
          plikd.cfg: |
            DownloadDomain = "dl.${SECRET_DOMAIN}"
            DataBackend = "file"
            [DataBackendConfig]
            Directory = "/files"
            MetadataBackend = "file"
            [MetadataBackendConfig]
            File = "/config/plik.db"
            FeatureAuthentication = "forced"  # Forces login for uploads; downloads remain public
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
        annotations:
          traefik.ingress.kubernetes.io/service.passhostheader: "true"  # Explicitly pass original Host header to backend
    ingress:
      main:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth@kubernetescrd"
        hosts:
          - host: &host "plik.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
      download:  # Added a second ingress for the download domain
        enabled: true
        className: traefik-external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth@kubernetescrd"
        hosts:
          - host: &host2 "dl.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host2
            secretName: "${SECRET_DOMAIN/./-}-production-tls"

    persistence:
      config:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 100Mi
      files:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 10Gi
      config-file:
        enabled: true
        type: configMap
        name: plik-config-file
        defaultMode: 0644
        advancedMounts:
          main:
            main:
              - path: /plikd.cfg
                subPath: plikd.cfg
                readOnly: true

    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
