# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plik
  namespace: media
spec:
  releaseName: plik
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      main:
        type: deployment
        strategy: Recreate
        containers:
          main:
            image:
              repository: rootgg/plik
              tag: 1.3.8
            env:
              TZ: ${TIMEZONE}
              PLIKD_DOWNLOAD_DOMAIN: "https://dl.${SECRET_DOMAIN}"
              PLIKD_DATA_BACKEND_CONFIG: '{"Directory":"/files"}'
              PLIKD_METADATA_BACKEND_CONFIG: '{"File":"/config/plik.db"}'
              PLIKD_FEATURE_AUTHENTICATION: "forced"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1028Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth@kubernetescrd"
        hosts:
          - host: &host "plik.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
      download:
        enabled: true
        className: traefik-external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth@kubernetescrd"
        hosts:
          - host: &host2 "dl.${SECRET_DOMAIN}"
            paths:
              - path: /file
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host2
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
    persistence:
      config:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 100Mi
      files:
        enabled: true
        storageClass: nfs-csi
        accessMode: ReadWriteMany
        size: 10Gi

    defaultPodOptions:
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: "Always"
