---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bjw-s.yaml
  - ./cilium.yaml
  - ./controlplaneio.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./emberstack-charts.yaml
  - ./external-dns.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./kubernetes-sigs-nfd-charts.yaml
  - ./k8s-gateway.yaml
  - ./nvidia-charts.yaml
  - ./metrics-server.yaml
  - ./openebs.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./traefik-charts.yaml
