apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.2
  share: /mnt/OlsonNAS/nfs/appdata
  subDir: "$${pvc.metadata.namespace}/$${pvc.metadata.name}"  # Escaped variables
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=16
  - hard
  - noatime
