---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app traefik-external
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 34.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    deployment:
      kind: Deployment
    updateStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 1
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 9
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 80
    service:
      enabled: true
      type: LoadBalancer
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "external.${SECRET_DOMAIN}"
        io.cilium/lb-ipam-ips: "${IPAM_IP_TRAEFIK_EXTERNAL}"
      spec:
        externalTrafficPolicy: Cluster
    env:
      - name: TZ
        value: "${TIMEZONE}"
    logs:
      general:
        level: INFO
      access:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: false
      name: traefik-external
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`ext-traefik.${SECRET_DOMAIN}`)
        entryPoints: ["websecure"]
        middlewares:
          - name: chain-no-auth-restrict-networks@kubernetescrd # network-chain-authentik-restrict-networks@kubernetescrd
        services: [{"kind":"TraefikService","name":"api@internal"}]
        tls:
          secretName: "${SECRET_DOMAIN/./-}-staging-tls"
    globalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--global.sendanonymoususage=false"
    additionalArguments:
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=0"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=0"
    ports:
      traefik:
        expose:
          default: false
      web:
        redirection:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
          options: default
        forwardedHeaders:
          trustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 108.162.192.0/18
            - 131.0.72.0/22
            - 141.101.64.0/18
            - 162.158.0.0/15
            - 172.64.0.0/13
            - 173.245.48.0/20
            - 188.114.96.0/20
            - 190.93.240.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 2400:cb00::/32
            - 2606:4700::/32
            - 2803:f800::/32
            - 2405:b500::/32
            - 2405:8100::/32
            - 2a06:98c0::/29
            - 2c0f:f248::/32
        proxyProtocol:
          trustedIPs:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 108.162.192.0/18
            - 131.0.72.0/22
            - 141.101.64.0/18
            - 162.158.0.0/15
            - 172.64.0.0/13
            - 173.245.48.0/20
            - 188.114.96.0/20
            - 190.93.240.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 2400:cb00::/32
            - 2606:4700::/32
            - 2803:f800::/32
            - 2405:b500::/32
            - 2405:8100::/32
            - 2a06:98c0::/29
            - 2c0f:f248::/32
        http3:
          enabled: true
      metrics:
        expose:
          default: false
    metrics:
      prometheus:
        entryPoint: metrics
        service:
          enabled: true
    pilot:
      enabled: false
    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowCrossNamespace: true
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
        publishedService:
          enabled: true
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app.kubernetes.io/instance: traefik-external
            app.kubernetes.io/component: controller
    resources:
      requests:
        cpu: 300m
        memory: 100M
      limits:
        cpu: 750m
        memory: 500M
    # experimental:
    #   plugins:
#        ldapAuth:
#          moduleName: "github.com/wiltonsr/ldapAuth"
#          version: "v0.1.8"
#        themepark:
#          moduleName: "github.com/packruler/traefik-themepark"
#          version: "v1.4.0"
        # bouncer:
        #   moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
        #   version: "v1.3.5"
        # traefik-plugin-blockuseragent:
        #   moduleName: "github.com/agence-gaya/traefik-plugin-blockuseragent"
        #   version: "v0.1.7"
    # volumes:
    #   - name: crowdsec-bouncer-tls
    #     mountPath: /etc/traefik/crowdsec-certs/
    #     type: secret
    #   - name: ban-html-page
    #     mountPath: /ban/
    #     type: configMap
    #   - name: captcha-html-page
    #     mountPath: /captcha/
    #     type: configMap
