---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app goldilocks
  namespace: &namespace observability
spec:
  chart:
    spec:
      chart: *app
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  interval: 15m
  dependsOn:
    - name: vpa
      namespace: observability
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /spec/containers/resources/limits
        target:
          kind: Pod
  values:
    image:
      repository: us-docker.pkg.dev/fairwinds-ops/oss/goldilocks
      tag: v4.13.3@sha256:e9a15845474a2c1d496d14c671bebfb8acb7104539cb54a972c1f09b9d278d47
      pullPolicy: Always

    controller:
      enabled: true
      resources:
        requests:
          cpu: 15m
          memory: 105Mi
        limits:
          memory: 132Mi

    dashboard:
      enabled: true
      replicaCount: 1
      # Container names to exclude from displaying in the Goldilocks dashboard
      ingress:
        main:
          enabled: true
          className: traefik-internal
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
            traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth@kubernetescrd"
          hosts:
            - host: "goldilocks.${SECRET_DOMAIN}"
              paths:
                - path: /
                  service:
                    identifier: main
                    port: http
          tls:
            - hosts:
                - "goldilocks.${SECRET_DOMAIN}"
              secretName: "${SECRET_DOMAIN/./-}-production-tls"
      resources:
        requests:
          cpu: 15m
          memory: 105Mi
        limits:
          memory: 105Mi

    annotations:
      reloader.stakater.com/search: "true"
