---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: kube-system
spec:
  interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  chart:
    spec:
      chart: reflector
      version: 7.1.288
      sourceRef:
        kind: HelmRepository
        name: emberstack-charts
        namespace: flux-system
      interval: 15m
