# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguardhome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: csi-driver-nfs
      namespace: storage
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  values:
    controllers:
      adguardhome:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: adguardhome
              storageClass: nfs-csi
              accessMode: ReadWriteMany
              size: 2Gi
              advancedMounts:
                app:
                  - path: /opt/adguardhome/conf
                    subPath: conf
                  - path: /opt/adguardhome/work
                    subPath: work
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.108.0-b.62
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              # capabilities:
              #   drop: ["ALL"]
            resources:
              requests:
                cpu: "50m"
                memory: "64Mi"
              limits:
                memory: "128Mi"
    service:
      adguardhome:
        controller: adguardhome
        type: LoadBalancer  # Use LoadBalancer to expose the service externally
        externalTrafficPolicy: Cluster # Allows Failover of Nodes # Local # Route external traffic to local pods
        annotations:
          io.cilium/lb-ipam-ips: "${IPAM_IP_ADGUARDHOME}"  # Use the IP from cluster-settings.yaml for external access
        ports:
          dns-udp:
            port: 53       # Add DNS UDP port
            protocol: UDP
          dns-tcp:
            port: 53       # Add DNS TCP port
            protocol: TCP
          dns-tcp-tls:
            port: 853      # Add DNS-over-TLS TCP port
            protocol: TCP
      adguardhome-internal:
        controller: adguardhome
        type: ClusterIP  # Use ClusterIP for internal DNS queries
        clusterIP: ${IPAM_IP_ADGUARDHOME_INTERNAL}
        ports:
          dns-udp-internal:
            port: 53
            protocol: UDP
          dns-tcp-internal:
            port: 53
            protocol: TCP
          dns-tcp-tls:
            port: 853      # Add DNS-over-TLS TCP port
            protocol: TCP
      adguardhome-webui:
        controller: adguardhome
        type: ClusterIP
        ports:
          http:
            port: 80       # Set to 3000 when setting up admin page, 80 after
            protocol: TCP
    ingress:
      adguardhome:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth@kubernetescrd"
        hosts:
          - host: "adguardhome.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: adguardhome-webui
                  port: http
        tls:
          - hosts:
              - "adguardhome.${SECRET_DOMAIN}"
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
