# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-3.2.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguardhome
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 10m
  values:
    controllers:
      adguardhome:
        type: statefulset
        statefulset:
          volumeClaimTemplates:
            - name: data
              storageClass: nfs-csi
              accessMode: ReadWriteOnce
              size: 10Gi
              advancedMounts:
                app:
                  - path: /opt/adguardhome/conf
                    subPath: conf
                  - path: /opt/adguardhome/work
                    subPath: work
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.108.0-b.62
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
            probes:
              liveness:
                enabled: true
                type: HTTP
                port: 3000
                path: /login.html
              readiness:
                enabled: true
                type: HTTP
                port: 3000
                path: /login.html
              startup:
                enabled: true
                type: HTTP
                port: 3000
                path: /login.html
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: "200m"
              limits:
                memory: "512Mi"
    service:
      adguardhome:
        controller: adguardhome
        ports:
          http:
            port: 3000
          dns-udp:  # Add DNS UDP port
            port: 53
            protocol: UDP
          dns-tcp:  # Add DNS-over-TLS TCP port
            port: 853
            protocol: TCP
    ingress:
      adguardhome:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: "network-chain-no-auth-restrict-networks@kubernetescrd"
        hosts:
          - host: "adguardhome.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: adguardhome
                  port: http
        tls:
          - hosts:
              - "adguardhome.${SECRET_DOMAIN}"
            secretName: "${SECRET_DOMAIN/./-}-production-tls"
