kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: gluetun-secret
  namespace: flux-system
stringData:
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:I3W+CxQ196hnQyeOmWkXFronVqzMK5s=,iv:F4DM0NvtkSztZVN+4/qhhXLF2F9LtH4VS4T5XZMlUfM=,tag:WqN/O6JPK9wDVAUmthTztw==,type:str]
  VPN_TYPE: ENC[AES256_GCM,data:Je4Dkc2KWBXX,iv:MM36HrddbyTzZ69qlmBPe38tZY5HXNASnlBHG2xHhuE=,tag:YekG58gXq9bXrFnGTJtaUg==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:PXEGlyOx,iv:KumjuvO77I0RXWHipn1W7eY+NqhrpRi1rnwbAGu7uTE=,tag:k8wtXMk5DBk2dox04f6BBw==,type:str]
  SERVER_CITIES: ENC[AES256_GCM,data:PBqU9qJMwg==,iv:9TJx5/8AsdbB4Y0Oy2MR5i/V3AHrSOTWyhoXKwnaaCw=,tag:Ek+BHu6/NjJUMraxCtjbAQ==,type:str]
  WIREGUARD_MTU: ENC[AES256_GCM,data:ZvEhKA==,iv:l5JuYI/DPWMrf8WxG68ItPkzLkXBCCoqeY41jREHXCg=,tag:mKFa44wdr34cqMGIKdfcng==,type:str]
  QBIT_USER: ENC[AES256_GCM,data:PBy311c=,iv:HKaVW7a9wnZmcNUJK4pqdHcJ+3Pa5+NBryCRyLp7iBo=,tag:JsW/Px7v4kwaClbWpjRP5A==,type:str]
  QBIT_PASS: ENC[AES256_GCM,data:2/xR5wqesVagKcKDXnuJBBY=,iv:aGMhPIwVQd88lS3AtmC1rLJmrFgGBbo+8IywbKc4U7E=,tag:8ct7KkDkTj8Iw4CiZ9DkyA==,type:str]
  PIA_USERNAME: ENC[AES256_GCM,data:b9GxcwaYwLI=,iv:SgAQlaLDwSfS2DbIGErwm+oEURy8rYasxIthC2kSrcI=,tag:+Iz9dOjWfKUYauWe89aRAg==,type:str]
  PIA_PASSWORD: ENC[AES256_GCM,data:F60rb9uf7LeX/PZon3mlsZ0=,iv:Wp3qOkmXuw2wyiVTDxQNuHXRhUXLrVBlk+DTE1A/3As=,tag:TxdHsLOFx60MTm18MOg24Q==,type:str]
  PRIVATE_INTERNET_ACCESS_PORT_FORWARDING_USERNAME: ENC[AES256_GCM,data:jLTXjzeQLvI=,iv:yFKm5OQ+VIf3DFbHzsHhrTWKTbcgCWKaJtyRVSYxbYs=,tag:Mr4h0i0BjqNTenBMqHoANA==,type:str]
  PRIVATE_INTERNET_ACCESS_PORT_FORWARDING_PASSWORD: ENC[AES256_GCM,data:E2lS8/LVXlFUmClCsIc=,iv:yNQV2FXKYeUAQhsegcy0NCwGKYqXVOitHCRAZJftRWU=,tag:HPhS3k+UxcFn/Pbc69N9zw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1h5suln4phcc5qzs2sfmkee39kzhdskmmwzzf5e46egaxqr64l9uskqeh4z
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETDliS2NaclljWlcwSnNo
        UnFTV1BiYlYxRHlkZ0I3NnVOVHEzU2YyOHpzCjhhZUt3dzBjTkd0MXFnU0tIc05N
        a1FXT3dBdDUyYmxha2lZdjVIb0xGa1UKLS0tIFI1alkyaHFHOW1odVJZb3paczdU
        UUUvVkNKWlEzK05DMlpxWE5WUlF3MGMKPiVmMbaTjkK6bM1xVzH++rhQF9EoKNKr
        ByzchgJR1Wst4i8j5TTBhKQV3P4rjkHqMxPAyRP1d85gqZDL0jG5Ag==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-06T22:08:02Z"
  mac: ENC[AES256_GCM,data:u4utWClv0+SODZ1AOocR+gaDn6LBRFCe5Jk1ZR3CdaAmzwHo2M/x74PPPyCBKHJOmuYcQxnxApS/VkD7WJI2zzz7pxaTCN/f8aean9xhXe0T4uV2+DEH+Iag/ARbctBMK6G8jKtUkqagRk6XeL1TVlga4ePNf6tE8vjSDGJzUuE=,iv:AFuLfZpw0FrnTpNsPg7F31WoxSdpNQwxTbhxBQFXuEw=,tag:g2sas1incU3fFpT4DLRHOg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.3
