---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gluetun
  namespace: network
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      gluetun:
        annotations:
          secret.reloader.stakater.com/reload: gluetun-secret

        pod:
          securityContext:
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          gluetun:
            image:
              repository: qmcgaw/gluetun
              tag: latest
            env:
              TZ: ${TIMEZONE}
              PORT_FORWARDING: "on"
              HTTP_SERVER: "on"  # API at :8000 for port queries
              SHADOWSOCKS: "on"  # SOCKS5 proxy at :1080 (encrypted via Shadowsocks)
              HTTPPROXY: "on"  # HTTP proxy at :8888
              FIREWALL: "on"
              FIREWALL_VPN_INPUT_PORT: "*"  # Allow all inbound for proxies/port forward
              # LOG_LEVEL: info
            envFrom:
              - secretRef:
                  name: gluetun-secret
            securityContext:
              runAsUser: 0
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              capabilities:
                add:
                  - NET_ADMIN  # For WireGuard/iptables
                drop:
                  - ALL
            resources:
              requests:
                cpu: 50m
                memory: 50M
              limits:
                cpu: 200m
                memory: 100M
                squat.ai/tun: 1  # TUN device limit

    service:
      main:  # Exposes proxies via ClusterIP (internal access only)
        controller: gluetun
        ports:
          http:  # HTTP proxy
            port: 8888
            targetPort: 8888
          socks5:  # Shadowsocks/SOCKS5
            port: 1080
            targetPort: 1080
          api:  # Port forward API
            port: 8000
            targetPort: 8000
          wireguard:  # wg0 for direct binds (if needed)
            port: 51820
            targetPort: 51820
            protocol: UDP

    persistence:
      config:
        enabled: true
        type: emptyDir  # Ephemeral for logs/state; use NFS if persistent needed
        advancedMounts:
          gluetun:
            gluetun:
              - path: /gluetun  # Gluetun config/logs
